config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :articles do
    resources :comments
  end

  resources :tags
  resources :authors
  resources :author_sessions, only: [:new, :create, :destroy]

  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  root 'articles#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments

  has_many :taggings
  has_many :tags, through: :taggings

  has_attached_file :image, styles: {medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png"]

  def tag_list
    tags.join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect {|tag_name| Tag.find_or_create_by({name: tag_name})}
    self.tags = new_or_found_tags
  end
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  before_action :require_login, except:  [:index, :show]
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])

    @comment = Comment.new
    @comment.article_id = @article.id

  end

  def new
    @article = Article.new
  end

  def create
    article = Article.create(article_params)
    flash.notice = "Article has successfully created"
    redirect_to article
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.update(article_params)
    flash.notice = "Article has successfully updated"
    redirect_to article_path(@article)
  end

  def destroy
    Article.destroy(params[:id])

    flash.notice = "Article has successfully destroyed"
    redirect_to articles_path
  end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  before_action :zero_authors_or_authenticated, only:  [:new, :create]
  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully')
    else
      flash.now.alert = "Login failed."
      render action: new
    end
  end

  def destroy
    logout
    redirect_to(:authors, notice: 'Logged out!')
  end

  def zero_authors_or_authenticated
    if Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]
  before_action :require_login, only: [:new, :create]
  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper
  before_action :require_login, only: [:create]
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_login, except: [:destroy]
  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end

  def destroy
    Tag.destroy(params[:id])
    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment">
    <%= comment.body %>
  </p>
  <p>
    <%= distance_of_time_in_words(Time.now, comment.created_at) %> ago
  </p>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "layouts/form" %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article),
                  class: 'article_title', id: "article_#{article.id}" %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a new article", new_article_path, class: 'new_article' %>

app/views/articles/new.html.erb
<h1>Create new Article</h1>

<%= render "layouts/form" %>

app/views/articles/show.html.erb
<h1>
  <%= @article.title %>
</h1>

<p>
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<p>
  <% if @article.image.exists? %>
    <%= image_tag @article.image.url %>
  <% end %>
</p>

<p class="article_body">
  <%= @article.body %>
</p>

<% if logged_in? %>
  <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Really delete article?"} %>
  <br>
  <%= link_to "Edit",  edit_article_path(@article)%>
  <br>
<% end %>
<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>

<%= render partial: 'comments/form' %>
<%= link_to 'Back to Articles', articles_path %>

app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </div>

  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login"%>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h3>Comment a post</h3>
<%= form_for [@article, @comment] do |f| %>
  <p>
    <%= f.label :author_name, 'Your Name' %>
    <%= f.text_field :author_name %>
  </p>

  <p>
    <%= f.label :body, 'Your comment' %>
    <%= f.text_field :body %>
  </p>
  <%= f.submit 'submit' %>
<% end %>

app/views/layouts/_flash.html.erb
<p class="flash">
  <%= flash.notice %>
</p>

app/views/layouts/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f|%>

  <ul>
    <% @article.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </ul>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %>
  </p>

  <p>
    <% if @article.image.exists?  %>
      <%= image_tag @article.image.url %><br>
    <% end %>

    <%= f.label :image, "Attach a new image" %>
    <%= f.file_field :image %>
  </p>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/flash" %>

    <div id="container">
      <div id="content">
        <%= yield %>
        <hr>
        <h6>
          <% if current_user %>
            <%= "Logged in as #{current_user.email}" %>
            <%= link_to '(logout)', logout_path %>
          <% else %>
            Logged Out
            <%= link_to '(login)', login_path %>
          <% end %>
        </h6>
      </div>
    </div>
  </body>
</html>

app/views/tags/index.html.erb
<h1>Tags</h1>

<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag),
          class: "tag_name", id: "tag_#{tag.id}"%>
    </li>
  <% end %>
</ul>

<%= link_to "back to articles", root_path %>

app/views/tags/show.html.erb
<h1>Articles tagged with: <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article.id) %>
    </li>
  <% end %>
</ul>

<%= link_to "delete tag", tag_path(@tag), method: :delete %>
<%= link_to "back to tags", tags_path %>